import { Session, SessionTask } from "./programmeSessions";
import { BASELINE_ANCHORS } from "./baseline";
import {
  ReducedLevel,
  REDUCTION_RULES,
  originalPrescription,
  prescriptionKind,
  reduceSetsAndReps,
} from "./reducedVolume";

/**
 * Programme adjustments driven by the athlete's own testing, and by the
 * current evidence on weighted-ball throwing.
 *
 * This is an overlay rather than an edit to the extracted programme. Two
 * reasons: `programmeContent.ts` is a machine extraction from the frozen v60
 * snapshot and is regenerated by `scripts/extract-programme.mjs`, so hand
 * edits there would be lost; and keeping the changes in one reviewable file
 * means a coach can audit exactly what was altered and why, against the
 * report line that justifies it.
 *
 * Every addition below traces to an explicit recommendation in the VALD
 * ForceDecks report. Nothing here is invented programming. What the reports
 * did not speak to — total session volume, what to drop to make room, the
 * balance between these additions and the existing lifts — is left alone,
 * because that is a coaching decision and not one the report makes.
 */

const [BOX_MIN, BOX_MAX] = BASELINE_ANCHORS.depthJumpBoxCm;
const [PCT_MIN, PCT_MAX] = BASELINE_ANCHORS.strengthPercentRange;

const GYM_STAGE_TITLES = ["Whole-Body Force", "Whole-Body Power"];

function round(value: number, to = 2.5) {
  return Math.round(value / to) * to;
}

/** Load window the report prescribes for the strength block. */
export function strengthWindowKg(oneRepMaxKg: number = BASELINE_ANCHORS.backSquat1RmKg) {
  return { low: round((oneRepMaxKg * PCT_MIN) / 100), high: round((oneRepMaxKg * PCT_MAX) / 100) };
}

/**
 * Reactive-strength work. The report names this as the primary limiter:
 * drop-jump RSI 0.96 (poor), ground contact 0.348 s against a sub-0.25 s
 * target. It prescribes low-box depth jumps with a stiffness and
 * contact-time focus.
 *
 * The existing primer's broad jump is a long-contact horizontal jump — it
 * trains the slow stretch-shortening cycle the athlete is already better at,
 * not the fast one the report flagged. This replaces it and keeps the
 * med-ball throw, so the primer stays a primer.
 */
function depthJumpTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  return {
    id: `${prefix}-depth-jump`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: `Depth jump — ${BOX_MIN}–${BOX_MAX} cm box`,
    prescription: "3 × 3 · full recovery · contact under 0.25 s",
    cue: "Minimise ground contact. Think stiff and quick off the floor, not high — height without a fast contact is the wrong adaptation.",
    setup: `Use a ${BOX_MIN}–${BOX_MAX} cm box on a non-slip surface with a clear landing area. Low box height is deliberate: the aim is contact time, not drop height.`,
    execution:
      "Step off — do not jump off — land and rebound immediately. Stop the set the moment contact time visibly lengthens or landings get noisy.",
    rest: "60–90 seconds between sets. This is a quality exposure, never conditioning.",
    stop: "Stop for any knee, ankle or Achilles pain, or when contacts slow. Fatigued depth jumps train the opposite of what this is for.",
  };
}

/**
 * Light-load, high-velocity squat work at the profile's optimal power load
 * (L0/2 = 94 kg). Prescribed by the report to target bar speed and rate of
 * force development directly.
 */
function velocitySquatTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  return {
    id: `${prefix}-velocity-squat`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: "Speed squat — optimal power load",
    prescription: `4 × 3 @ ${BASELINE_ANCHORS.optimalPowerLoadKg} kg · every rep maximal intent`,
    cue: "The load is fixed; the only variable is how fast the bar moves. Stop the set when bar speed drops.",
    setup: `${BASELINE_ANCHORS.optimalPowerLoadKg} kg is the measured optimal load for peak power (L0/2 from the load-velocity profile). Use a rack with safeties.`,
    execution:
      "Controlled descent, then accelerate as hard as possible through the whole concentric. Reset between reps rather than bouncing them together.",
    rest: "2–3 minutes. Power work needs full recovery to stay power work.",
    stop: "End the set on any drop in bar speed, or for pain. Grinding reps here defeats the purpose.",
  };
}


/**
 * The anterior-chain strength lift the report prescribes and the session did
 * not have.
 *
 * ForceDecks asked for a progressive back squat at 4–8 reps × 3–5 sets,
 * 77–87% of max, with bar-speed intent. Nothing in the gym block sat in that
 * window: the trap bar runs 6 × 2, and the speed squat is 94 kg — 65% of max,
 * deliberately light because it trains bar speed, not strength.
 *
 * The load comes from the tested 145 kg rather than an estimate, which is the
 * whole reason the testing was worth wiring in.
 *
 * This raises Monday's lower-body count to four loaded movements — squat,
 * trap bar, split squat and RDL. That is a real cost and it is a coaching
 * decision, not one this file should make silently; it is flagged rather than
 * resolved by dropping something on its own initiative.
 */
function backSquatTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  const window = strengthWindowKg();
  return {
    id: `${prefix}-back-squat`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: "Back squat",
    prescription: `4 × 5 @ ${window.low}–${window.high} kg · ${PCT_MIN}–${PCT_MAX}% of tested max`,
    cue: "Drive the bar with intent on every rep. Depth consistent, brace before the descent.",
    setup: `From a rack with safeties. ${window.low}–${window.high} kg is ${PCT_MIN}–${PCT_MAX}% of the tested ${BASELINE_ANCHORS.backSquat1RmKg} kg max — start at the bottom of the window and progress across the block.`,
    execution:
      "Controlled down, fast up. Stop the set if bar speed drops sharply or depth changes, rather than grinding a rep out.",
    rest: "3 minutes between work sets.",
    stop: "End the set for loss of spinal position or knee pain, or if bar speed collapses.",
  };
}

/**
 * Posterior-chain hinge. Named directly in the report's strength block
 * alongside the squat.
 *
 * It sits on Thursday, and the reason is competition timing rather than the
 * label on the day. An RDL is the most eccentric-biased movement in the week
 * and therefore the likeliest to produce delayed soreness, which peaks at
 * 24–48 hours. Thursday puts it 48 hours from Saturday's first pitch; Friday
 * would put it 24, which is the worst case.
 *
 * Friday is also the wrong character for it. Everything there — pogo,
 * vertical jump, landmine push press at RPE 5–6, split-squat isometric — is
 * sub-maximal and fast, deliberately potentiating. A loaded hinge changes
 * what that day is. And dropping the RDL to Friday's intensity to make it fit
 * would leave it rehearsing the pattern rather than training it, which
 * defeats the point of placing it at all.
 *
 * RPE 7, not 7–8: a genuine stimulus, but Thursday is still a recovery day
 * and the top of that range does not belong on one.
 */
function rdlTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  const window = strengthWindowKg();
  return {
    id: `${prefix}-rdl`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: "Romanian deadlift",
    prescription: `3 × 6 @ RPE 7 · hinge to mid-shin`,
    cue: "Push the hips back and keep the bar close. Feel the hamstrings load rather than the lower back.",
    setup: `Barbell from a rack at hip height. For reference, the report's strength window on the tested squat max is ${window.low}–${window.high} kg; the RDL is loaded by feel against that, not by the same percentage.`,
    execution:
      "Soft knees, long spine, bar tracking the legs. Drive the floor away to stand. Deliberate tempo down, purposeful up.",
    rest: "2 minutes.",
    stop: "Stop for lower-back pain, loss of spinal position, or hamstring cramping.",
  };
}

/**
 * Bar-speed intent cueing on primary strength lifts.
 *
 * The report calls this out explicitly to address a 354 ms time to peak
 * force. It changes nothing about the load or the set count — only what the
 * athlete is trying to do with the bar — so it is applied as an annotation
 * rather than as a new prescription.
 */
const BAR_SPEED_LIFTS = ["deadlift", "squat", "bench press", "push press"];

function withBarSpeedIntent(task: SessionTask): SessionTask {
  const name = task.name.toLowerCase();
  if (!BAR_SPEED_LIFTS.some((lift) => name.includes(lift))) return task;
  if (task.name.toLowerCase().includes("speed squat")) return task;
  return {
    ...task,
    cue: `${task.cue} Move the bar with maximal intent on every concentric, even at heavy loads — testing flagged a slow 354 ms time to peak force.`,
    execution: `${task.execution ?? ""} Intent matters as much as the load here: the bar should be driven, not lifted.`.trim(),
  };
}

/**
 * Evidence note carried by every plyo-ball task.
 *
 * Weighted-ball throwing is the least settled part of this programme. A
 * randomised trial of high-school pitchers (Reinold et al., 2018) reported a
 * 24% injury rate in the weighted-ball group against none in the control,
 * along with a 4.3° gain in shoulder external rotation; an interim study of
 * 88 minor-league pitchers (2025) found higher arm and trunk injury
 * prevalence (39.1% vs 23.8%) and roughly double the days lost among users.
 *
 * That evidence does not make sub-maximal constraint work indefensible —
 * which is how most of these throws are prescribed here — but it does mean
 * the athlete should see it rather than have it decided for them.
 */
export const PLYO_EVIDENCE_NOTE =
  "Evidence note: weighted-ball throwing is contested. A randomised trial of high-school pitchers (Reinold et al., 2018) found a 24% injury rate in the weighted-ball group versus none in the control, alongside a 4.3° increase in shoulder external rotation. An interim 2025 study of 88 minor-league pitchers found higher arm and trunk injury prevalence (39.1% vs 23.8%) and about twice the days lost among users. Risk concentrates in maximal-intent light-ball throwing rather than sub-maximal constraint work. Review this block with your coach and medical team before progressing intent or volume.";

function withPlyoEvidence(task: SessionTask): SessionTask {
  if (task.stageTitle !== "Plyo Ball Preparation") return task;
  // The 2 kg ball had its own note; it is now removed outright, so the only
  // remaining caveat is the light-ball one.
  const light = /1[0-2]?[05]\s*g\b/.test(task.name) && !/1,?000\s*g/.test(task.name);
  const extra = light
    ? " Light balls produce the highest arm speeds and are where the reported injury risk concentrates."
    : "";
  return { ...task, stop: `${task.stop ?? ""} ${PLYO_EVIDENCE_NOTE}${extra}`.trim() };
}

/**
 * Apply everything to a built session.
 *
 * Order matters only in that the additions land inside the gym stage, so
 * they inherit its heading and stay grouped with the rest of the lift.
 */
/**
 * State the reduced dose instead of describing how to compute it.
 *
 * The programme replaces a prescription with guidance when readiness drops —
 * "Remove the final work set · use no more than 90% of the listed load".
 * That is arithmetic handed to a fatigued athlete mid-session. The numbers
 * come first now, with the rule that produced them kept underneath so the
 * reasoning is still visible and the original is still one tap away.
 */
function withExplicitReducedDose(level: ReducedLevel | null) {
  return (task: SessionTask): SessionTask => {
    if (!level || !task.adapted) return task;
    const original = originalPrescription(task.adaptationNote);
    if (!original) return task;

    const kind = prescriptionKind(task.stageTitle, task.name);
    const explicit = reduceSetsAndReps(original, kind, level);
    // Nothing parseable means nothing to state. Guessing a set count here
    // would be worse than leaving the guidance the programme wrote.
    if (!explicit) return task;

    return {
      ...task,
      prescription: explicit,
      cue: `${REDUCTION_RULES[level][kind]} ${task.cue}`,
      adaptationNote: `${task.adaptationNote} · Reduced to ${explicit}.`,
    };
  };
}


/**
 * The 2 kg plyo ball, removed at the athlete's request.
 *
 * It appeared once — Monday's reverse throw, 1 × 5 at 50% — as low-intent
 * patterning work. It goes for two reasons. It is heavier than any implement
 * used in the injury and velocity trials this programme cites (Reinold's RCT
 * topped out at 32 oz / 907 g; the 2025 professional cohort reported 4–9 oz),
 * so there is no evidence base for that specific load. And the 1,000 g
 * reverse throw immediately after it does the same job, which means nothing
 * has to be invented to replace it.
 *
 * Kept as a named rule rather than an edit to the extracted programme:
 * `programmeContent.ts` is regenerated from the frozen v60 snapshot, so an
 * edit there would be silently undone on the next extraction.
 */
const REMOVED_IMPLEMENTS = [/2,?000\s*g/];

function isRemovedImplement(task: SessionTask): boolean {
  return task.stageTitle === "Plyo Ball Preparation"
    && REMOVED_IMPLEMENTS.some((pattern) => pattern.test(task.name));
}

/**
 * The trap bar deadlift comes off Monday.
 *
 * Once the tested back squat is in at 77–87%, Monday carries two heavy
 * bilateral primaries back to back — roughly twenty heavy squat reps and
 * twelve heavy pulls of axial load, on a day that also throws 45–60 balls.
 * Neither lift progresses cleanly when they compete for the same recovery,
 * and the trap bar's 6 × 2 only does its job if the bar moves fast, which it
 * will not do behind a squat at 87%.
 *
 * The hinge is not lost: the RDL is on Thursday and the single-leg RDL on
 * Wednesday, so the pattern is covered twice a week. The squat pattern was
 * covered zero times before the testing added it. And the trap bar itself
 * survives on Wednesday as the jump variant, where its speed-strength intent
 * is actually preserved.
 */
function isDisplacedByBackSquat(task: SessionTask, day: number | null): boolean {
  return day === DAY_MONDAY && /^Trap bar deadlift$/.test(task.name);
}


// --- Weekly distribution ----------------------------------------------------

/**
 * Where each addition belongs in the week.
 *
 * Everything the testing called for was landing on Monday, which already
 * carried seven lifts, while Tuesday ran speed work only and Thursday carried
 * no loading at all. That is not a programme, it is one hard day and three
 * light ones — and it is the opposite of what the MFT profile suggested, which
 * was that this athlete tolerates frequency.
 *
 * So the work is spread:
 *
 *  Monday    reactive + heavy strength. The primary force day.
 *  Wednesday bar-speed work. Wednesday is already the power day — med-ball,
 *            jumps, push press — so the speed squat belongs with them, not
 *            stacked behind Monday's heavy squat.
 *  Thursday  the posterior-chain hinge, as a microdose. Thursday had no
 *            loading whatsoever, and an RDL is cheap systemically: it fits
 *            beside recovery work without competing with it.
 *
 * Friday is left alone — it is the pre-game microdose and already exists.
 * Saturday is competition, Sunday is rest.
 */
const DAY_MONDAY = 0;
const DAY_WEDNESDAY = 2;
const DAY_THURSDAY = 3;

// --- Supersets --------------------------------------------------------------

/**
 * Pairs that should be run together, and — just as important — what must not.
 *
 * Antagonist and non-competing pairs cost nothing in quality and buy back a
 * lot of session time, which is the difference between an eleven-item Monday
 * being done and being abandoned halfway.
 *
 * Nothing that depends on being fresh is paired: the heavy squat, the trap
 * bar, the depth jump and the speed squat all run straight, because density
 * degrades exactly the qualities they train. A superset there would quietly
 * convert strength and power work into conditioning.
 */
const SUPERSET_RULES: { day: number; group: string; members: RegExp[] }[] = [
  {
    day: DAY_MONDAY,
    group: "A",
    members: [/^Bench press$/, /^Chest-supported dumbbell row$/],
  },
  {
    day: DAY_MONDAY,
    group: "B",
    members: [/^Nordic hamstring curl$/, /Pallof press/],
  },
  {
    day: DAY_WEDNESDAY,
    group: "A",
    members: [/^Push press$/, /^Chin-up$/],
  },
  {
    day: DAY_WEDNESDAY,
    group: "B",
    members: [/Single-leg Romanian deadlift/, /cable chop/i],
  },
];

/** Movements that must never be paired, whatever else is going on. */
const NEVER_SUPERSET = [/Back squat/, /Speed squat/, /Depth jump/, /Trap bar/];

function withSupersets(day: number | null) {
  return (task: SessionTask): SessionTask => {
    if (day === null) return task;
    if (NEVER_SUPERSET.some((pattern) => pattern.test(task.name))) return task;

    const rule = SUPERSET_RULES.find(
      (candidate) => candidate.day === day && candidate.members.some((m) => m.test(task.name))
    );
    if (!rule) return task;

    const position = rule.members.findIndex((m) => m.test(task.name)) + 1;
    const partners = rule.members.length;
    return {
      ...task,
      superset: `${rule.group}${position}`,
      supersetOf: partners,
      rest:
        position < partners
          ? "No rest — go straight into the next movement in this superset."
          : `${task.rest ?? ""} Rest here, then return to ${rule.group}1.`.trim(),
    };
  };
}


// --- Warm-up additions ------------------------------------------------------

/**
 * Daily ankle-stiffness microdose.
 *
 * The warm-up went from mobility straight into plyo throws or a barbell with
 * no elastic exposure at all. For most athletes that is a small omission. For
 * this one it is the flagged limiter: soleus carnosine at Z −1.51 (the lowest
 * value in the MFT scan), drop-jump ground contact of 0.348 s against a
 * sub-0.25 s target, and 354 ms to peak force. The soleus is the ground-
 * contact muscle and it is the weakest tissue on the report.
 *
 * That quality was trained twice a week — Friday's pogos and Monday's depth
 * jumps. This is the classic case for a microdose: about a minute, negligible
 * fatigue cost, and it tolerates daily frequency, so it runs every day the
 * session has a warm-up. Sunday has no warm-up stage and correctly gets none.
 *
 * Deliberately low amplitude. This primes stiffness; it is not a jump session,
 * and the depth jumps on Monday remain the actual training dose.
 */
function ankleStiffnessTask(prefix: string): SessionTask {
  return {
    id: `${prefix}-ankle-stiffness`,
    stage: 1,
    stageTitle: "Prepare",
    stageDescription: "Raise temperature before mobility or throwing.",
    name: "Ankle stiffness pogos",
    prescription: "2 × 10 · low amplitude · minimal ground contact",
    cue: "Stiff ankles, quiet landings, barely leave the floor. Speed off the ground beats height every rep.",
    setup: "Firm, non-slip surface. Stand tall, weight through the midfoot.",
    execution:
      "Bounce from the ankles with the knees almost straight. Think of the floor as hot. Stop the set if contacts get heavy or slow.",
    rest: "30 seconds between sets. This is priming, not conditioning.",
    stop: "Stop for Achilles, calf or heel pain. Soreness here is a reason to skip it, not to push through.",
  };
}

/**
 * Forearm and wrist prep, before throwing rather than after it.
 *
 * The programme has forearm pronation and supination in the post-throw arm
 * care circuit but nothing pre-throw, so the tissue that decelerates the wrist
 * and takes the valgus load through the elbow went into the first throw cold.
 * Cheap to fix and it belongs immediately before the throwing prep.
 */
function forearmPrepTask(prefix: string): SessionTask {
  return {
    id: `${prefix}-forearm-prep`,
    stage: 1,
    stageTitle: "Prepare",
    stageDescription: "Raise temperature before mobility or throwing.",
    name: "Wrist and forearm prep",
    prescription: "Wrist circles 10/direction · pronation–supination 10/side · light gripper or towel squeeze 10",
    cue: "Light and full-range. This wakes the forearm up; it is not a training set.",
    setup: "No load, or the lightest implement available.",
    execution: "Move through comfortable range at an easy tempo, both directions.",
    rest: "Straight into the throwing prep.",
    stop: "Stop for medial elbow or wrist pain — that is a reason to review the day, not to warm up harder.",
  };
}

/**
 * Hip preparation, which the warm-up barely touched.
 *
 * The mobility flow already has the ankle rock, the 90/90 switch, the adductor
 * rock, the World's Greatest Stretch and the open book — a good general flow,
 * and it stays exactly as it is. What it does not have is anything that asks
 * the hip to *produce* rotation rather than be moved through it, anything for
 * hip extension range, and anything for the lateral hip that holds the pelvis
 * level when the lead leg lands.
 *
 * That matters more for a pitcher than for most athletes. In nineteen
 * professional pitchers measured with fluid goniometry against 3-D motion
 * capture, the total rotation arc of the *non-dominant* hip — the lead leg —
 * correlated with ball velocity at r = 0.50, and the pitchers had significantly
 * less passive range on that side than on the dominant one across every
 * direction measured (Robb 2010). Nineteen subjects and a correlation is not a
 * training study, and this is not sold as one: it is a reason to spend three
 * minutes on the lead hip, not a promise of velocity.
 *
 * Deliberately no end-range adductor loading. The flow's adductor rock covers
 * that gently, and a Cossack squat in a warm-up is where a groin gets pulled.
 */
function hipPrepTask(prefix: string): SessionTask {
  return {
    id: `${prefix}-hip-prep`,
    stage: 1,
    stageTitle: "Prepare",
    stageDescription: "Raise temperature before mobility or throwing.",
    name: "Hip prep — rotation and glutes",
    prescription:
      "Half-kneeling hip flexor with posterior tilt 2 × 20 s/side · 90/90 internal rotation lift-off 6/side · lateral band walk 10 steps each way · single-leg glute bridge 8/side",
    cue: "Own the range rather than sink into it. Every rep is your own muscle moving the joint, not gravity. The lift-off uses the same 90/90 position as the switch in the flow above and does the opposite job: that one moves you through the range, this one makes you hold the end of it under your own power.",
    setup:
      "A mat or soft surface for the kneeling and bridging work, and a light band above the knees for the walks.",
    execution:
      "Half-kneeling hip flexor: back knee down, tuck the tailbone under until you feel the front of the hip, then stay tall — do not arch to get deeper. 90/90 lift-off: sit in the 90/90 position and lift the back shin off the floor without leaning, hold a second, lower under control. Lateral band walk: knees out, feet quiet, small steps. Single-leg glute bridge: drive through the heel, keep the pelvis level, no arch through the lower back.",
    rest: "Straight through — this is a warm-up, not a set.",
    stop: "Stop for groin or front-of-hip pinching. Pinching at end of range means less range today, not more effort.",
    evidence:
      "Robb 2010, Am J Sports Med — 19 professional pitchers, fluid goniometry with 3-D motion analysis. Total rotation arc of the non-dominant (lead) hip correlated with ball velocity, r = 0.50; the non-dominant hip had less passive range than the dominant one in every direction measured. Correlational, and small.",
  };
}

/**
 * Trunk and spine preparation, and the one drill here with real evidence
 * behind it.
 *
 * The warm-up prepared the shoulder, the forearm and the ankle, and left the
 * segment between them out. The gap that matters is not spinal mobility — the
 * open book covers thoracic rotation — but lumbopelvic *control*: whether the
 * pelvis holds its position when the athlete stands on one leg, which is the
 * position a pitcher is in for the whole delivery.
 *
 * That was measured prospectively in 347 professional pitchers across five
 * organisations. Pitchers whose pelvis deviated 8° or more during a single-leg
 * raise were three times more likely to miss thirty days or more to injury
 * than those under 4°, and among pitchers who did get hurt, the worst-control
 * group averaged 98.6 days missed against 43.8 (Chaudhari 2014). That is one
 * of the largest effects in the whole pitching-injury literature, and it is
 * measured on a test that costs nothing to rehearse.
 *
 * So the last drill here is deliberately the test itself, held rather than
 * scored. Bird dog and the side plank are left out on purpose — they belong to
 * the soreness protocol's lower-back prescription, and putting them in both
 * places would give a sore back the same exercise twice on the same day.
 */
function trunkPrepTask(prefix: string): SessionTask {
  return {
    id: `${prefix}-trunk-prep`,
    stage: 1,
    stageTitle: "Prepare",
    stageDescription: "Raise temperature before mobility or throwing.",
    name: "Trunk and spine prep",
    prescription:
      "Cat-camel 8 slow · dead bug 6/side · single-leg pelvic-control hold 2 × 20 s/side",
    cue: "The last one is the one that counts. Pelvis dead level, and nothing above the hips moves.",
    setup: "A mat for the first two. For the hold, stand tall with something at hand's reach to touch if you wobble.",
    execution:
      "Cat-camel: move one segment at a time, slowly, through the whole spine — this is motion, not a stretch. Dead bug: press the lower back into the floor and keep it there as the opposite arm and leg reach away; the moment the back lifts, you have found your range. Single-leg pelvic-control hold: come to the single-leg stance you pitch from and hold with the pelvis level — no hip drop, no tilt, no arch. Watch the front of your hips in a mirror or a window if you have one.",
    rest: "No rest needed. Move on when the last hold is clean.",
    stop: "Stop for lower-back pain rather than working through it, and report it on the daily plan so tomorrow is adjusted.",
    evidence:
      "Chaudhari 2014, Am J Sports Med 42(11):2734–2740 — prospective, 347 professional pitchers across five organisations. Pelvic deviation ≥8° on a single-leg raise carried a 3.0× risk of missing 30+ days versus <4°; among those injured, that group averaged 98.6 days missed against 43.8 in the best-controlled group.",
  };
}

export function applyBaselineProgramming(
  session: Session,
  level: ReducedLevel | null = null,
  day: number | null = null
): Session {
  const tasks = session.tasks
    .filter((task) => !isRemovedImplement(task))
    .filter((task) => !isDisplacedByBackSquat(task, day))
    .map(withBarSpeedIntent)
    .map(withPlyoEvidence)
    .map(withSupersets(day))
    .map(withExplicitReducedDose(level));

  // Warm-up additions run every day that has a warm-up. Sunday has no
  // Prepare stage and correctly receives nothing.
  const prepEnd = tasks.map((task) => task.stageTitle).lastIndexOf("Prepare");
  if (prepEnd !== -1) {
    const prepPrefix = String(tasks[0].id).split("-").slice(0, 2).join("-");
    const absent = (addition: SessionTask) => !tasks.some((task) => task.id === addition.id);
    const regional = [hipPrepTask(prepPrefix), trunkPrepTask(prepPrefix)].filter(absent);
    const tail = [ankleStiffnessTask(prepPrefix), forearmPrepTask(prepPrefix)].filter(absent);

    // Order is general to specific, and it is not cosmetic. The stage after
    // this one is always throwing or sprinting, so what the athlete does last
    // is what carries into the first throw.
    //
    // The two regional blocks go in beside the general mobility flow, *not* at
    // the end of the stage. Appended, they landed between "Scapular and cuff
    // activation" and the throwing — putting six minutes of hip and trunk work
    // between the shoulder being primed and the first ball leaving the hand,
    // and displacing the most throwing-specific piece of the warm-up into the
    // middle of it.
    //
    // Two inserts rather than one, later index first so the earlier splice
    // does not shift it:
    //
    //   raise → general mobility → hips → trunk → cuff → ankle → forearm
    tasks.splice(prepEnd + 1, 0, ...tail);

    const flowIndex = tasks.findIndex(
      (task) => task.stageTitle === "Prepare" && /mobility flow/i.test(task.name)
    );
    tasks.splice(flowIndex === -1 ? prepEnd + 1 : flowIndex + 1, 0, ...regional);
  }

  let gymIndex = tasks.findIndex((task) => GYM_STAGE_TITLES.includes(task.stageTitle));

  // Thursday carries no gym stage at all, which is exactly why it was chosen
  // for the microdose — but it means there is no stage to insert into. Create
  // one rather than silently dropping the work.
  if (gymIndex === -1) {
    const wantsWork = day === DAY_THURSDAY;
    if (!wantsWork) return { ...session, tasks };
    const after = tasks.filter((task) => task.stage <= 4).length;
    tasks.splice(after, 0, {
      id: `${String(tasks[0]?.id ?? "day").split("-").slice(0, 2).join("-")}-microdose`,
      stage: 4,
      stageTitle: "Whole-Body Force",
      stageDescription: "Microdose — one hinge, kept cheap so it does not compete with recovery.",
      name: "Microdose block",
      prescription: "One movement, done well",
      cue: "This is a small, deliberate dose on an otherwise unloaded day. Do not turn it into a session.",
    });
    gymIndex = after;
  }

  const { stageTitle, stageDescription } = tasks[gymIndex];
  const prefix = String(tasks[gymIndex].id).split("-").slice(0, 2).join("-");

  // The primer's broad jump trains the slow SSC the athlete already has.
  // Swap it for the depth jump the report asked for, keeping the med-ball
  // throw so the primer remains a primer.
  const primerIndex = tasks.findIndex((task) => /primer/i.test(task.name));
  if (primerIndex !== -1) {
    const primer = tasks[primerIndex];
    tasks[primerIndex] = {
      ...primer,
      prescription: primer.prescription.replace(/·?\s*broad jump[^·]*/i, "").replace(/·\s*$/, "").trim(),
      cue: `${primer.cue} Broad jumps were replaced by depth jumps below: testing flagged fast stretch-shortening, not horizontal power, as the limiter.`,
    };
  }

  // Placement is not cosmetic here. Reactive and velocity work has to happen
  // while the athlete is fresh: a depth jump after a heavy deadlift trains a
  // slow contact, which is the exact quality the testing flagged as the
  // limiter. So these go early — right behind the primer, ahead of the heavy
  // strength work — and only the hinge goes at the end with the accessories.
  // A null day means "wherever this session is" — used by tests and by any
  // caller that has not said. It gets everything, as before.
  const onMonday = day === null || day === DAY_MONDAY;
  const onWednesday = day === null || day === DAY_WEDNESDAY;
  const onThursday = day === null || day === DAY_THURSDAY;

  const early = [
    ...(onMonday ? [depthJumpTask(prefix, stageTitle, stageDescription)] : []),
    ...(onWednesday ? [velocitySquatTask(prefix, stageTitle, stageDescription)] : []),
    // Heavy strength follows the velocity work: light-and-fast first, then
    // load. The reverse order leaves the fast work fatigued.
    ...(onMonday ? [backSquatTask(prefix, stageTitle, stageDescription)] : []),
  ].filter((addition) => !tasks.some((task) => task.id === addition.id));

  const late = (onThursday ? [rdlTask(prefix, stageTitle, stageDescription)] : []).filter(
    (addition) => !tasks.some((task) => task.id === addition.id)
  );

  let lastGym = gymIndex;
  for (let i = tasks.length - 1; i >= 0; i -= 1) {
    if (GYM_STAGE_TITLES.includes(tasks[i].stageTitle)) {
      lastGym = i;
      break;
    }
  }
  tasks.splice(lastGym + 1, 0, ...late);

  // After whatever prepares for it: the named primer on Monday, the jumps on
  // Wednesday. The jumps are the most neurally demanding thing in that
  // session and have to come first, so the speed squat follows them rather
  // than displacing them.
  const anchor = tasks.findIndex((task) => /primer/i.test(task.name) || /broad jump/i.test(task.name));
  tasks.splice(anchor === -1 ? gymIndex : anchor + 1, 0, ...early);

  return { ...session, tasks };
}
