import { Session, SessionTask } from "./programmeSessions";
import { BASELINE_ANCHORS } from "./baseline";

/**
 * Programme adjustments driven by the athlete's own testing, and by the
 * current evidence on weighted-ball throwing.
 *
 * This is an overlay rather than an edit to the extracted programme. Two
 * reasons: `programmeContent.ts` is a machine extraction from the frozen v60
 * snapshot and is regenerated by `scripts/extract-programme.mjs`, so hand
 * edits there would be lost; and keeping the changes in one reviewable file
 * means a coach can audit exactly what was altered and why, against the
 * report line that justifies it.
 *
 * Every addition below traces to an explicit recommendation in the VALD
 * ForceDecks report. Nothing here is invented programming. What the reports
 * did not speak to — total session volume, what to drop to make room, the
 * balance between these additions and the existing lifts — is left alone,
 * because that is a coaching decision and not one the report makes.
 */

const [BOX_MIN, BOX_MAX] = BASELINE_ANCHORS.depthJumpBoxCm;
const [PCT_MIN, PCT_MAX] = BASELINE_ANCHORS.strengthPercentRange;

const GYM_STAGE_TITLES = ["Whole-Body Force", "Whole-Body Power"];

function round(value: number, to = 2.5) {
  return Math.round(value / to) * to;
}

/** Load window the report prescribes for the strength block. */
export function strengthWindowKg(oneRepMaxKg: number = BASELINE_ANCHORS.backSquat1RmKg) {
  return { low: round((oneRepMaxKg * PCT_MIN) / 100), high: round((oneRepMaxKg * PCT_MAX) / 100) };
}

/**
 * Reactive-strength work. The report names this as the primary limiter:
 * drop-jump RSI 0.96 (poor), ground contact 0.348 s against a sub-0.25 s
 * target. It prescribes low-box depth jumps with a stiffness and
 * contact-time focus.
 *
 * The existing primer's broad jump is a long-contact horizontal jump — it
 * trains the slow stretch-shortening cycle the athlete is already better at,
 * not the fast one the report flagged. This replaces it and keeps the
 * med-ball throw, so the primer stays a primer.
 */
function depthJumpTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  return {
    id: `${prefix}-depth-jump`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: `Depth jump — ${BOX_MIN}–${BOX_MAX} cm box`,
    prescription: "3 × 3 · full recovery · contact under 0.25 s",
    cue: "Minimise ground contact. Think stiff and quick off the floor, not high — height without a fast contact is the wrong adaptation.",
    setup: `Use a ${BOX_MIN}–${BOX_MAX} cm box on a non-slip surface with a clear landing area. Low box height is deliberate: the aim is contact time, not drop height.`,
    execution:
      "Step off — do not jump off — land and rebound immediately. Stop the set the moment contact time visibly lengthens or landings get noisy.",
    rest: "60–90 seconds between sets. This is a quality exposure, never conditioning.",
    stop: "Stop for any knee, ankle or Achilles pain, or when contacts slow. Fatigued depth jumps train the opposite of what this is for.",
  };
}

/**
 * Light-load, high-velocity squat work at the profile's optimal power load
 * (L0/2 = 94 kg). Prescribed by the report to target bar speed and rate of
 * force development directly.
 */
function velocitySquatTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  return {
    id: `${prefix}-velocity-squat`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: "Speed squat — optimal power load",
    prescription: `4 × 3 @ ${BASELINE_ANCHORS.optimalPowerLoadKg} kg · every rep maximal intent`,
    cue: "The load is fixed; the only variable is how fast the bar moves. Stop the set when bar speed drops.",
    setup: `${BASELINE_ANCHORS.optimalPowerLoadKg} kg is the measured optimal load for peak power (L0/2 from the load-velocity profile). Use a rack with safeties.`,
    execution:
      "Controlled descent, then accelerate as hard as possible through the whole concentric. Reset between reps rather than bouncing them together.",
    rest: "2–3 minutes. Power work needs full recovery to stay power work.",
    stop: "End the set on any drop in bar speed, or for pain. Grinding reps here defeats the purpose.",
  };
}

/**
 * Posterior-chain hinge. Named directly in the report's strength block
 * alongside the squat.
 */
function rdlTask(prefix: string, stageTitle: string, stageDescription: string): SessionTask {
  const window = strengthWindowKg();
  return {
    id: `${prefix}-rdl`,
    stage: 4,
    stageTitle,
    stageDescription,
    name: "Romanian deadlift",
    prescription: `3 × 6 @ RPE 7–8 · hinge to mid-shin`,
    cue: "Push the hips back and keep the bar close. Feel the hamstrings load rather than the lower back.",
    setup: `Barbell from a rack at hip height. For reference, the report's strength window on the tested squat max is ${window.low}–${window.high} kg; the RDL is loaded by feel against that, not by the same percentage.`,
    execution:
      "Soft knees, long spine, bar tracking the legs. Drive the floor away to stand. Deliberate tempo down, purposeful up.",
    rest: "2 minutes.",
    stop: "Stop for lower-back pain, loss of spinal position, or hamstring cramping.",
  };
}

/**
 * Bar-speed intent cueing on primary strength lifts.
 *
 * The report calls this out explicitly to address a 354 ms time to peak
 * force. It changes nothing about the load or the set count — only what the
 * athlete is trying to do with the bar — so it is applied as an annotation
 * rather than as a new prescription.
 */
const BAR_SPEED_LIFTS = ["deadlift", "squat", "bench press", "push press"];

function withBarSpeedIntent(task: SessionTask): SessionTask {
  const name = task.name.toLowerCase();
  if (!BAR_SPEED_LIFTS.some((lift) => name.includes(lift))) return task;
  if (task.name.toLowerCase().includes("speed squat")) return task;
  return {
    ...task,
    cue: `${task.cue} Move the bar with maximal intent on every concentric, even at heavy loads — testing flagged a slow 354 ms time to peak force.`,
    execution: `${task.execution ?? ""} Intent matters as much as the load here: the bar should be driven, not lifted.`.trim(),
  };
}

/**
 * Evidence note carried by every plyo-ball task.
 *
 * Weighted-ball throwing is the least settled part of this programme. A
 * randomised trial of high-school pitchers (Reinold et al., 2018) reported a
 * 24% injury rate in the weighted-ball group against none in the control,
 * along with a 4.3° gain in shoulder external rotation; an interim study of
 * 88 minor-league pitchers (2025) found higher arm and trunk injury
 * prevalence (39.1% vs 23.8%) and roughly double the days lost among users.
 *
 * That evidence does not make sub-maximal constraint work indefensible —
 * which is how most of these throws are prescribed here — but it does mean
 * the athlete should see it rather than have it decided for them.
 */
export const PLYO_EVIDENCE_NOTE =
  "Evidence note: weighted-ball throwing is contested. A randomised trial of high-school pitchers (Reinold et al., 2018) found a 24% injury rate in the weighted-ball group versus none in the control, alongside a 4.3° increase in shoulder external rotation. An interim 2025 study of 88 minor-league pitchers found higher arm and trunk injury prevalence (39.1% vs 23.8%) and about twice the days lost among users. Risk concentrates in maximal-intent light-ball throwing rather than sub-maximal constraint work. Review this block with your coach and medical team before progressing intent or volume.";

function withPlyoEvidence(task: SessionTask): SessionTask {
  if (task.stageTitle !== "Plyo Ball Preparation") return task;
  const heavy = /2,?000\s*g/.test(task.name);
  const light = /1[0-2]?[05]\s*g\b/.test(task.name) && !/1,?000\s*g/.test(task.name);
  const extra = heavy
    ? " This ball is heavier than any implement used in the published trials, so there is no evidence base for it specifically."
    : light
      ? " Light balls produce the highest arm speeds and are where the reported injury risk concentrates."
      : "";
  return { ...task, stop: `${task.stop ?? ""} ${PLYO_EVIDENCE_NOTE}${extra}`.trim() };
}

/**
 * Apply everything to a built session.
 *
 * Order matters only in that the additions land inside the gym stage, so
 * they inherit its heading and stay grouped with the rest of the lift.
 */
export function applyBaselineProgramming(session: Session): Session {
  const tasks = session.tasks.map(withBarSpeedIntent).map(withPlyoEvidence);

  const gymIndex = tasks.findIndex((task) => GYM_STAGE_TITLES.includes(task.stageTitle));
  if (gymIndex === -1) return { ...session, tasks };

  const { stageTitle, stageDescription } = tasks[gymIndex];
  const prefix = String(tasks[gymIndex].id).split("-").slice(0, 2).join("-");

  // The primer's broad jump trains the slow SSC the athlete already has.
  // Swap it for the depth jump the report asked for, keeping the med-ball
  // throw so the primer remains a primer.
  const primerIndex = tasks.findIndex((task) => /primer/i.test(task.name));
  if (primerIndex !== -1) {
    const primer = tasks[primerIndex];
    tasks[primerIndex] = {
      ...primer,
      prescription: primer.prescription.replace(/·?\s*broad jump[^·]*/i, "").replace(/·\s*$/, "").trim(),
      cue: `${primer.cue} Broad jumps were replaced by depth jumps below: testing flagged fast stretch-shortening, not horizontal power, as the limiter.`,
    };
  }

  // Placement is not cosmetic here. Reactive and velocity work has to happen
  // while the athlete is fresh: a depth jump after a heavy deadlift trains a
  // slow contact, which is the exact quality the testing flagged as the
  // limiter. So these go early — right behind the primer, ahead of the heavy
  // strength work — and only the hinge goes at the end with the accessories.
  const early = [
    depthJumpTask(prefix, stageTitle, stageDescription),
    velocitySquatTask(prefix, stageTitle, stageDescription),
  ].filter((addition) => !tasks.some((task) => task.id === addition.id));

  const late = [rdlTask(prefix, stageTitle, stageDescription)].filter(
    (addition) => !tasks.some((task) => task.id === addition.id)
  );

  let lastGym = gymIndex;
  for (let i = tasks.length - 1; i >= 0; i -= 1) {
    if (GYM_STAGE_TITLES.includes(tasks[i].stageTitle)) {
      lastGym = i;
      break;
    }
  }
  tasks.splice(lastGym + 1, 0, ...late);

  // After the primer if there is one, otherwise at the head of the gym block.
  const primerAt = tasks.findIndex((task) => /primer/i.test(task.name));
  tasks.splice(primerAt === -1 ? gymIndex : primerAt + 1, 0, ...early);

  return { ...session, tasks };
}
