import { BASELINE_ANCHORS } from "./baseline";

/**
 * Monday's primary lift, periodised again.
 *
 * When the tested back squat went in, the trap bar deadlift came off Monday —
 * two heavy bilateral primaries back to back on a day that also throws 45–60
 * balls is not a session either lift progresses through. That call stands. But
 * the trap bar was carrying something nobody noticed it was carrying: the
 * programme's entire week-to-week periodisation.
 *
 * `programmeContent.ts` holds a fifty-two-week table of `[sets, reps, percent]`
 * — a real block plan, with accumulation, intensification, strength-speed and
 * deload weeks — and it was only ever read to price the trap bar. With the trap
 * bar gone from Monday, that table went unread, and the squat that replaced it
 * was a fixed `4 × 5` at a fixed window derived from the 145 kg tested max. So
 * every Monday of the winter block prescribed identical work: week 7,
 * "Strength-speed peak", read exactly the same as week 1, "Baseline quality".
 * The label and the session disagreed for eight weeks.
 *
 * This reads that table and applies it to the squat instead.
 *
 * ## Two deliberate departures
 *
 * **Reps have a floor of four.** The table's strength-speed weeks are doubles,
 * and the ForceDecks report asked for the squat at 4–8 reps × 3–5 sets. A
 * double is a good trap bar prescription and a poor squat one at this athlete's
 * training age. Where the table asks for fewer than four, the reps come up to
 * four and the *sets come down to match the original total*, so the volume
 * curve the block was built on survives intact:
 *
 *     week 5  6 × 2 = 12 reps  →  3 × 4 = 12 reps
 *     week 8  4 × 2 =  8 reps  →  2 × 4 =  8 reps
 *
 * Without that second half the deload disappears: clamping reps alone turns
 * both weeks into `4 × 4` and the athlete's easy week becomes their hardest.
 *
 * **The percentage is relative intensity, not a load claim.** The table's
 * percentages are of a trap bar training max, and they are applied here to the
 * squat's own tested max. What carries across is the *shape* — which weeks are
 * heavy, which are light, and by how much — not an equivalence between the two
 * lifts. The check that matters is where it lands: across the winter block the
 * squat comes out at 79–86% of the tested 145 kg, inside the report's 77–87%
 * window. In-season summer weeks fall below it, and that is correct — those are
 * maintenance weeks and the programme's own table says so.
 */

export type LiftSpec = readonly [sets: number, reps: number, percent: number];

/**
 * The programme's own fifty-two-week block plan.
 *
 * Copied, not imported: `programmeContent.ts` is machine-extracted from the
 * frozen v60 snapshot, carries `@ts-nocheck`, is regenerated by
 * `scripts/extract-programme.mjs`, and does not export this table. Rather than
 * edit a generated file, the copy is checked against the original by a test
 * that reads the source as text — so the two cannot drift apart quietly.
 */
export const WEEK_SPECS: Readonly<Record<number, LiftSpec>> = {
  1: [4, 5, 80], 2: [4, 5, 82], 3: [5, 3, 85], 4: [5, 3, 87],
  5: [6, 2, 80], 6: [6, 2, 82], 7: [6, 2, 83], 8: [4, 2, 77],
  9: [3, 5, 65], 10: [3, 4, 70], 11: [4, 3, 75], 12: [3, 2, 70],
  13: [3, 3, 75], 14: [3, 3, 77], 15: [3, 3, 78], 16: [2, 3, 70],
  17: [3, 3, 77], 18: [3, 2, 80], 19: [3, 3, 75], 20: [2, 3, 70],
  21: [3, 2, 78], 22: [2, 2, 70], 23: [3, 5, 70], 24: [4, 5, 75],
  25: [4, 4, 78], 26: [5, 3, 82], 27: [5, 3, 85], 28: [3, 3, 70],
  29: [3, 3, 75], 30: [3, 3, 77], 31: [3, 2, 80], 32: [2, 3, 70],
  33: [3, 3, 77], 34: [3, 2, 80], 35: [2, 2, 72], 36: [2, 2, 67],
  37: [3, 5, 60], 38: [3, 4, 65], 39: [4, 5, 78], 40: [4, 5, 80],
  41: [5, 3, 83], 42: [5, 3, 85], 43: [6, 2, 78], 44: [6, 2, 80],
  45: [6, 2, 82], 46: [4, 2, 72], 47: [4, 3, 75], 48: [4, 3, 77],
  49: [4, 2, 78], 50: [3, 2, 70], 51: [4, 2, 75], 52: [3, 2, 70],
};

/** The report's rep floor for the squat. Below this it stops being the lift it asked for. */
export const SQUAT_MIN_REPS = 4;

/** Never fewer than two work sets — one set of four is a warm-up with a number on it. */
const MIN_SETS = 2;

export interface SquatDose {
  sets: number;
  reps: number;
  /** Of the tested squat max, carried across from the table as relative intensity. */
  percent: number;
  kg: number;
  /** What the week is for, from the table's own rep scheme. */
  character: "Accumulation" | "Intensification" | "Strength-speed";
  /** True where the reps were raised to the report's floor and sets rebalanced. */
  rebalanced: boolean;
}

function round(value: number, to = 2.5) {
  return Math.round(value / to) * to;
}

/**
 * The week's squat, or null where there is no week to read.
 *
 * Null rather than a guess: a caller that does not know its week should keep
 * whatever the programme wrote, not receive week 1's dose by default.
 */
export function squatDose(
  week: number | null,
  oneRepMaxKg: number = BASELINE_ANCHORS.backSquat1RmKg
): SquatDose | null {
  if (week === null) return null;
  const spec = WEEK_SPECS[week];
  if (!spec) return null;

  const [specSets, specReps, percent] = spec;
  const reps = Math.max(SQUAT_MIN_REPS, specReps);
  const rebalanced = reps > specReps;
  // Total reps are the block's volume curve, and the whole point of raising the
  // rep count is that it must not raise the week's work.
  const sets = rebalanced
    ? Math.max(MIN_SETS, Math.round((specSets * specReps) / reps))
    : specSets;

  return {
    sets,
    reps,
    percent,
    kg: round((oneRepMaxKg * percent) / 100),
    character: specReps >= 5 ? "Accumulation" : specReps >= 3 ? "Intensification" : "Strength-speed",
    rebalanced,
  };
}

/** A week the programme itself calls a deload, a taper, an unload or a review. */
export function isEasyWeek(focus: string | null | undefined): boolean {
  return /deload|unload|taper|review/i.test(String(focus ?? ""));
}
